version: '3'
services:
  db:
    build: .
    container_name: thumb-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      